service: bookmgr-api-books

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-aws-documentation
  - serverless-import-apigateway
  - serverless-offline

functions:
  get_books:
    handler: handler.get_books
    events:
      - http:
          path: books
          method: get
          documentation:
            summary: Get Books
            description: Get Books
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: "Book Response"
                responseModels:
                  "application/json": "BookResponse"

custom:

  importApiGateway:
    name: ${opt:stage, self:provider.stage}-bookmgr-api-gateway

  documentation:
    models:
      - name: "BookResponse"
        description: "Get Books Response"
        contentType: "application/json"
        schema:
          type: "array"
          items:
            type: "object"
            properties:
              title:
                type: "string"
              author:
                type: "string"
