serverless-offline:
  httpPort: 4000

tables:
  dynamo:
    # Dynamo options
    deploymentBatchSize: 5

dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
  stages:
    - dev
  start:
    port: 8000
    inMemory: true
    heapInitial: 200m
    heapMax: 1g
    migrate: true
    convertEmptyValues: true

  seed:
    domain:
      sources:
        - table: books
          sources: [ ./data/books.json ]

pythonRequirements:
  layer: true
  noDeploy:
    - pytest
    - boto3
