service: bookmgr-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

plugins:
  - fullstack-serverless

custom:

  fullstack:
    domain: www.melkouhen.me
    certificate: arn:aws:acm:us-east-1:629923658207:certificate/c2519af3-3275-466d-96f9-0986b2398a83
    bucketName: bookmgr-app-2020
    distributionFolder: build
    indexDocument: index.html
    errorDocument: error.html
    singlePageApp: true
    compressWebContent: true
    apiPath: /${opt:stage, self:provider.stage}
    apiGatewayRestApiId: ${cf:bookmgr-api-${opt:stage, self:provider.stage}.AwsDocApiId}
    clientCommand: yarn build
    clientSrcPath: .
    priceClass: PriceClass_100
    noConfirm: true

