service: bookmgr-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-aws-documentation
  - serverless-apigateway-plugin

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          documentation:
            summary: Ping
            description: Ping
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: "Ping Response"
                responseModels:
                  "application/json": "PingResponse"

custom:

  documentation:
    api:
      info:
        version: '1'
        title: 'Book API'
        description: 'Book API'

    models:
      - name: "PingResponse"
        description: "Ping Response"
        contentType: "application/json"
        schema:
          type: "object"
          properties:
            ping:
              type: "string"
