service: bookmgr-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-openapi-documentation
  - serverless-aws-documentation
  - serverless-apigateway-plugin
  - serverless-stack-output
  - serverless-offline

functions:
  list_books:
    handler: handler.list_books
    events:
      - http:
          path: books
          method: get
          cors: true
          documentation:
            summary: List Books
            description: List Books
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "Book Response"
                responseModels:
                  "application/json": "BookResponse"

custom:
  openApiPath: openapi.yml

  documentation:
    api:
      info:
        version: '1'
        title: 'Book API'
        description: 'Book API'

    models:
      - name: "BookResponse"
        description: "Book Response"
        contentType: "application/json"
        schema:
          type: "object"
          properties:
            title:
              type: "string"
            author:
              type: "string"

  serverless-offline:
      httpPort: 4000