service: bookmgr-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-aws-documentation
  - serverless-openapi-documentation
  - serverless-apigateway-plugin
  - serverless-plugin-tables
  - serverless-dynamodb-local
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-python-requirements


functions:
  list_books:
    handler: handler.list_books
    iamRoleStatementsName: bookmgr-api-list-books-${opt:stage, self:provider.stage}-role
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:scan
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/books"
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: books
          method: get
          documentation:
            summary: List Books
            description: List Books
            methodResponses:
              - statusCode: '200'
                responseBody:
                  description: "Book Response"
                responseModels:
                  "application/json": "BookResponse"

resources:
  tables:
    books:
      partitionKey: author
      sortKey: title
      indexes:
        - name: authorByTitleIndex
          partitionKey: author
          sortKey: title

custom:

  documentation:
    api:
      info:
        version: '1'
        title: 'Book API'
        description: 'Book API'

    models:
      - name: "BookResponse"
        description: "Book Response"
        contentType: "application/json"
        schema: ${file(schemas/BooksResponse.yml)}

  tables: ${file(config.yml):tables}

  serverless-offline: ${file(config.yml):serverless-offline}

  dynamodb: ${file(config.yml):dynamodb}

  pythonRequirements: ${file(config.yml):pythonRequirements}
